# tasks: ['simple_prompt', 'diverse_prompt', 'MS-COCO', 'selective_alignment', 'over_erasing', 
#         'bias', 'sketch2image', 'image2image', 'concept_restoration']
tasks: ['bias']

method: 'esd'
device: 'cuda:0'
seed: 0

bias:
  target_class: 0   # 0 ~ 9
  n_samples: 10000
  batch_size: 50
  use_cond: False