# tasks: ['simple_prompt', 'diverse_prompt', 'MS-COCO', 'selective_alignment', 'over_erasing', 
#         'bias', 'sketch2image', 'image2image', 'concept_restoration']
# tasks: ['sketch2image', 'image2image', 'concept_restoration']
tasks: ['selective_alignment']

target: church
method: 'esd'
device: 'cuda:0'
seed: 0

concept_restoration:
  start_t_idx: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45]  # 0 means that concept restoration begins at t=1.0, which is a noise distribution. The denoising process is divided into 50 steps between 0 and 1, with each step size being 20.