data:
    path: ./data
    dataset: MNIST
    image_size: 28
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: true
    num_workers: 4
    n_classes: 10

model:
    type: simple
    in_channels: 1
    out_ch: 1
    ch: 128
    ch_mult: [1, 2, 2, 2]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: False
    resamp_with_conv: True
    cond_drop_prob: 0.1

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    visualization_samples: 100

sampling:
    batch_size: 512
    last_only: True

comments: nil